spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
       max-file-size: 10MB
       max-request-size: 10MB